language: cpp
sudo: required
dist: trusty

# NOTE: The COMPILER variable is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
  include:
    # - clang w/ libc++
    # - release
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test

    # - clang w/ libc++
    # - debug
    # - ASAN, USAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - DEBUG=1 ASAN=1 USAN=1

    # - clang w/ libc++
    # - debug
    # - MSAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - DEBUG=1 MSAN=1

    # - clang w/ libc++
    # - debug
    # - TSAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - DEBUG=1 TSAN=1

    # - g++
    # - release
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - CXX=g++-6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libboost-test-dev

before_script:
  - ./install_cmake.sh
  - ./install_llvm.sh
  - ./install_benchmark.sh

cache:
  # Use a one week timeout 60 * 24 * 7 = 10080 min:
  timeout: 10080
  directories:
    - llvm
    - benchmark

script:
  - make

notifications:
  email: false
