language: cpp
sudo: required
dist: trusty

# NOTE: The COMPILER variable is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
  include:
    # Clang w/ libc++
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
      env:
        - DEBUG=1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libboost-test-dev
  - git clone https://github.com/google/benchmark.git
  - cd benchmark
  - cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_USE_LIBCXX=ON -DCMAKE_CXX_FLAGS="-I/usr/include/c++/v1" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
  - make install

script:
  - make
