language: cpp
sudo: required
dist: trusty

# NOTE: The COMPILER variable is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
  include:
    # - clang w/ libc++
    # - release
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8
        - BENCHMARK_FLAGS="-stdlib=libc++"

    # - clang w/ libc++
    # - debug
    # - ASAN, USAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 DEBUG=1 ASAN=1 USAN=1
        - BENCHMARK_FLAGS="-stdlib=libc++"

    # - clang w/ libc++
    # - debug
    # - TSAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 DEBUG=1 TSAN=1
        - BENCHMARK_FLAGS="-stdlib=libc++"

    # - g++
    # - release
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=gcc-6 CXX_COMPILER=g++-6
        - BENCHMARK_FLAGS="-fuse-ld=gold"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libboost-test-dev

before_script:
  - ./install_cmake.sh
  - CC=$C_COMPILER CXX=$CXX_COMPILER ./install_llvm.sh
  - CC=$C_COMPILER CXX=$CXX_COMPILER ./install_benchmark.sh
  - if [ -n "$COVERAGE" ]; then ./install_coverage.sh fi

script:
  - CC=$C_COMPILER CXX=$CXX_COMPILER make

after_success:
  - if [ -n "$COVERAGE" ]; then ./upload_coverage.sh fi

notifications:
  email: false
