language: cpp
sudo: required
dist: trusty

# NOTE: The COMPILER variable is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
    include:
    # - clang w/ libc++
    # - release
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8
        - LIBCXX=1
        - BENCHMARK_FLAGS="-stdlib=libc++"
        - BUILD_TYPE=release

    # - clang w/ libc++
    # - debug
    # - ASAN, USAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8
        - LIBCXX=1
        - BENCHMARK_FLAGS="-stdlib=libc++"
        - BUILD_TYPE=asan_usan
        - ASAN_OPTIONS=detect_leaks=0 # boost unit_test has leaks :(

    # - clang w/ libc++
    # - debug
    # - TSAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8
        - LIBCXX=1
        - BENCHMARK_FLAGS="-stdlib=libc++"
        - BUILD_TYPE=tsan

    # - clang w/ libc++
    # - debug + log
    # - TSAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8
        - LIBCXX=1
        - BENCHMARK_FLAGS="-stdlib=libc++"
        - BUILD_TYPE=tsan
        - LOG=1

    # - g++
    # - release
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=gcc-6 CXX_COMPILER=g++-6
        - BENCHMARK_FLAGS="-fuse-ld=gold"
        - BUILD_TYPE=release

    # - g++
    # - coverage
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=gcc-6 CXX_COMPILER=g++-6 GCOV=gcov-6
        - BUILD_TYPE=coverage
        - COVERAGE=1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libboost-test-dev
  - sudo apt-get install -y --force-yes libboost-filesystem1.62-dev
  - sudo apt-get install -y gdb

before_script:
  - ./install_coverage.sh
  - ./install_cmake.sh
  - CC=${C_COMPILER} CXX=${CXX_COMPILER} ./install_llvm.sh
  - CC=${C_COMPILER} CXX=${CXX_COMPILER} ./install_benchmark.sh
  - ulimit -c unlimited -S # enable core dumps

script:
  - mkdir build
  - cd build
  - cmake --version
  - which cmake
  - CC=${C_COMPILER} CXX=${CXX_COMPILER} cmake -DUSE_LIBCXX=${LIBCXX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLOG=${LOG} ..
  - make -j2 VERBOSE=1
  - ./tests/unit_tests --show_progress --log_level=test_suite
  - ./tests/stress_tests --show_progress --log_level=test_suite
  - if [ "${BUILD_TYPE}" == "release" ]; then
      ./tests/perf_tests;
    fi
  - ./examples/basic1
  - cd ..

after_success:
  - ./upload_coverage.sh

after_failure:
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
  - if [[ -f "${COREFILE}" ]]; then gdb -c "${COREFILE}" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

notifications:
  email: false
