language: cpp
sudo: required
dist: trusty

# NOTE: The COMPILER variable is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
  include:
    # - clang w/ libc++
    # - release
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8
        - LIBCXX=1
        - BENCHMARK_FLAGS="-stdlib=libc++"

    # - clang w/ libc++
    # - debug
    # - ASAN, USAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 DEBUG=1 ASAN=1 USAN=1
        - LIBCXX=1
        - BENCHMARK_FLAGS="-stdlib=libc++"

    # - clang w/ libc++
    # - debug
    # - TSAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 DEBUG=1 TSAN=1
        - LIBCXX=1
        - BENCHMARK_FLAGS="-stdlib=libc++"

    # - clang w/ libc++
    # - debug + log
    # - TSAN
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 DEBUG=1 LOG=1 TSAN=1
        - LIBCXX=1
        - BENCHMARK_FLAGS="-stdlib=libc++"

    # - g++
    # - release
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=gcc-6 CXX_COMPILER=g++-6
        - BENCHMARK_FLAGS="-fuse-ld=gold"

    # - g++
    # - coverage
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test
      env:
        - C_COMPILER=gcc-6 CXX_COMPILER=g++-6 GCOV=gcov-6
        - COVERAGE=1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libboost-test-dev

before_script:
  - ./install_coverage.sh
  - ./install_cmake.sh
  - CC=$C_COMPILER CXX=$CXX_COMPILER ./install_llvm.sh
  - CC=$C_COMPILER CXX=$CXX_COMPILER ./install_benchmark.sh

script:
  - mkdir build
  - cd build
  - CC=${C_COMPILER} CXX=${CXX_COMPILER} cmake -DUSE_LIBCXX=${LIBCXX} ..
  - make -j2 VERBOSE=1
  - ./tests/unit_tests --show_progress --log_level=test_suite
  - ./tests/stress_tests --show_progress --log_level=test_suite
  - if [ -z "${TSAN}" ]; then
      ./tests/perf_tests;
    fi

after_success:
  - ./upload_coverage.sh

notifications:
  email: false
