language: cpp
sudo: required
dist: trusty

# NOTE: The COMPILER variable is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
  include:
    # Clang w/ libc++
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
      env:
        - DEBUG=1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libboost-test-dev

script:
  - make
